### ISSUE TITLE
Support find-references

### ISSUE THREAD

**Issue by meditans** [haskell/ghcide#10]
The `find-references` feature doesn't seem to work right out of the box. What's needed to make this feature work?

**Comment by meditans** [comment]
Any news on the pieces that we would need for this @ndmitchell? When you say the `set of roots` would just the list of files that are loaded in ghcide be enough?

**Comment by mpickering** [comment]
@meditans We are making progress towards this issue certainly. One issue to overcome is that you really don't want to keep a lot of every information about every module in memory as it causes too much memory usage so creating an out of memory cache is important.

**Comment by meditans** [comment]
Thanks @mpickering, I just read the weekly update and went back to check this issue. You're doing an amazing job in helping the ide infrastructure moving forward!

**Comment by jneira** [comment]
Maybe related with "goto reference": https://github.com/haskell/haskell-language-server/issues/211
It seems the commits referencing this issue are not related.

**Comment by jneira** [comment]
This should be fixed by #898

**Comment by jneira** [comment]
@meditans as this repo is about to be archived we are gonna include this one in https://github.com/haskell/ghcide/pull/898
