### ISSUE TITLE
"stack script" support or workarounds?

### ISSUE THREAD

**Issue by ethercrow** [haskell/ghcide#162]
I have some scripts written using `stack script` interpreter, which conveniently takes care of installing packages my scripts depend on. Understandably, ghcide is not aware of this, but maybe I can do something to make it aware?

Is writing a `hie.yaml` something I need here? Didn't have to do that yet for other, non-script projects.

This is how it looks currently:
![Screenshot 2019-10-10 at 09 50 15](https://user-images.githubusercontent.com/222467/66549336-62891d00-eb43-11e9-96a2-3a1d4793a284.png)

**Comment by cocreature** [comment]
Does `stack script` have a way to load the script into ghci? That should make it fairly easy to add support for this to `hie-bios` which we use to setup the GHC environment.

**Comment by jared-w** [comment]
@cocreature stack script does indeed support the ability to load something into ghci. [Full details here](https://docs.haskellstack.org/en/stable/GUIDE/#loading-scripts-in-ghci)

Relevant snippet:

A script (with program omitted):

```haskell
#!/usr/bin/env stack
{- stack
  script
  --resolver lts-8.2
  --package turtle
-}
```

As far as i can tell, this is the equivalent to load it up into ghci:

```haskell
#!/usr/bin/env stack
{- stack
     --resolver lts-8.2
     --install-ghc
     exec ghci
     --package turtle
-}
```

With stack script, the resolver should already be there (not that I think ghcide actually needs it?) And the ghcide already knows where ghc is or it wouldn't be running in the first place. So it seems like figuring out how to shove things into GHCi automatically shouldn't be too difficult? Famous last words, of course.

**Comment by andys8** [comment]
I was also looking into this. Another related problem is using `ghcide` with "standalone" haskell configuration files with `xmonad` or `xmobar`. It'll complain about missing packages, too. If stack scripts would work, it might be a workaround for this issue, too.

For now my "workaround" is to add `package.yaml` and `stack.yaml` with all dependencies to make `ghcide` happy.

**Comment by fendor** [comment]
Stack scripts are supported in a hacky way. 
You have to add an explicit `hie.yaml` file with the contents:
```yaml
cradle:
  stack:
    component: "File.hs"
```

Works fine for loading and modifying the stack script.
However, if you modify the script section, these changes wont be detected, e.g. you have to restart ghcide/hls

**Comment by jneira** [comment]
related: https://github.com/mpickering/hie-bios/issues/217

**Comment by jneira** [comment]
closinf in favour of https://github.com/haskell/haskell-language-server/issues/111
