### ISSUE TITLE
Failed to start VSCode extension in Stack project

### ISSUE THREAD

**Issue by NickSeagull** [haskell/ghcide#183]
Hey, thanks for this great effort. I've installed `ghcide` and it works when ran in the console for a newly created Stack project:

```text
ghcide version: 0.0.4 (GHC: 8.6.5)
Ghcide setup tester in /home/nick/dev/ghcide-test.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/nick/dev/ghcide-test
Found 3 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /home/nick/dev/ghcide-test
Cradle {cradleRootDir = "/home/nick/dev/ghcide-test", cradleOptsProg = CradleAction: stack}

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files

Completed (3 files worked, 0 files failed)
```

But when opening VSCode with `stack exec -- code .` I get the following error:

```text
[Error - 1:27:16 PM] Starting client failed
Launching server using command stack exec -- ghcide --lsp failed.
```

Doesn't matter which command I configure in VSCode, `ghcide`, `stack exec ghcide`, or the `stack exec -- ghcide --lsp`, it always fails with the same error.

Any tips on how to debug this?

I'm running this under Ubuntu 18.04 under WSL.

**Comment by cocreature** [comment]
Try running `stack install` to install `ghcide` into `~/.local/bin`, make sure that is in `PATH` (note that changes to `PATH` need to be visible to VSCode so if you change `.bashrc` make sure that you start VSCode such that it sees the changes (easiest might be to reboot)) and then set it to `ghcide`.

**Comment by NickSeagull** [comment]
Thanks for the suggestion! Sadly it didn't work :(

Any ideas about what could be the next steps? What additional information could I provide in order to help?

**Comment by cocreature** [comment]
What does `which ghcide` show you?
Also which folder did you open? You probably want to open the one containing `hie.yaml`.

**Comment by NickSeagull** [comment]
> What does which ghcide show you?

```
~/dev/ghcide-test
❯ which ghcide
/home/nick/.local/bin/ghcide
```

> Also which folder did you open? You probably want to open the one containing hie.yaml.
I'm opening the root of the newly created project, I added a `hie.yaml` containing the following with no avail.

```text
cradle: {stack}
```

The `tree -L 1` output is:

```text
.
├── ChangeLog.md
├── LICENSE
├── README.md
├── app
├── ghcide-test.cabal
├── hie.yaml
├── package.yaml
├── src
├── stack.yaml
├── stack.yaml.lock
└── test
```

**Comment by cocreature** [comment]
I’m afraid, I’m starting to run out of ideas. This is using `ghcide` as the location of the executable and `--lsp` as the arguments in the extension settings, right?

**Comment by cocreature** [comment]
Oh yeah, I wouldn’t be surprised if that breaks.

**Comment by NickSeagull** [comment]
Lately I just default to WSL by default, as things usually work better on that side. I'm going to try seeing if `ghcide` works in Emacs, and in Windows, will report back 😄

**Comment by NickSeagull** [comment]
Ok, apparently Emacs connects properly to `ghcide` using `eglot`, trying VSCode from Windows now

**Comment by NickSeagull** [comment]
Apparently doesn't work on VSCode on Windows either.

What I've found is that if I run VSCode by using `stack exec code`, it will fail with the message above.
But if I run it out of stack, by just running `code` it will fail saying that it doesn't find `ghc` (which makes sense).

I just added to the PATH variable the `ghc` installation path and it worked. Still I believe that the errors are a bit misleading

**Comment by ndmitchell** [comment]
Sorry, I've got a bit lost with all the talk of WSL. Can you summarise what the problem was and how you fixed it? If possible, as a patch to https://github.com/digital-asset/ghcide/blob/master/docs/Setup.md? It would be good to collect whatever information you learnt from this adventure. Sounds like using WSL and remote connect are both bad ideas? If so, that seems worth documenting.

**Comment by NickSeagull** [comment]
@ndmitchell I've switched from WSL to regular Windows, but it still didn't work, what I ended up doing was adding `C:\Users\nikit\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.5\bin` to my `PATH`.

Now `ghcide` works, unless I open up a project that uses another version of `ghc` that is not `8.6.5`.

I didn't close the issue because I don't consider this fixed. `ghcide` doesn't pickup the `stack` `PATH` in any environment on my side.

**Comment by cocreature** [comment]
This is related to https://github.com/digital-asset/ghcide/issues/137. Afaik, we don’t assume that GHC is in PATH ourselves but `hie-bios` does.

**Comment by Ciantic** [comment]
I'm getting this in Windows:

```ghcide.exe: ghc: readCreateProcess: does not exist (No such file or directory)```

Maybe this is related to `hie-bios` too, expecting ghc to be in PATH.

**Comment by jneira** [comment]
This might be solved in newer versions, that improves tool discovering (or you could use the haskell vscode extension)
