### ISSUE TITLE
Why important that ghcide compiled with same compiler used to build projects?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/ghcide#196]
The README says

> It's important that ghcide is compiled with the same compiler you use to build your projects.

Could you augment that sentence with "because ..."?  It's not clear whether it's a simple matter of convenience "because otherwise you may get error messages that don't apply to your build and miss error messages that do" or there's something more serious going on.

**Comment by cocreature** [comment]
GHC isn’t able to load interface files from other versions so if you compile ghcide with a different version of GHC we won’t be able to load your dependencies which makes it pretty much unusable.

**Comment by tomjaguarpaw** [comment]
I don't understand.  Why would `ghcide` try to load interface files compiled from another GHC version?  Doesn't it keep its own build around in its own `--builddir`?

**Comment by cocreature** [comment]
ghcide will never write files to disk at the moment. For dependencies we rely on `cabal`, `stack`, … (via `hie-bios`) to build them and then point the GHC API to those package dbs so if `cabal` uses a different version of GHC those package dbs will be incompatible with `ghcide`. For the project you are currently working on, everything is kept in memory.

**Comment by i-am-the-slime** [comment]
How can you even control which ghc version you use to compile ghcide? Do I need to change the `resolver` value in `stack.yaml`?

**Comment by cocreature** [comment]
@i-am-the-slime yep, that’s exactly it.

**Comment by jneira** [comment]
I think the question(s) was answered, so closing
