### ISSUE TITLE
fatal error: ghc-api-version.h: No such file or directory

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/ghcide#198]
I'm using Emacs 26.3 and the lsp-ui install instructions on the ghcide README.

I can't get `ghcide` to work on itself! I get the error `fatal error: ghc-api-version.h: No such file or directory`.  That `.h` file is indeed in the repository in `include/`.  How can I persuade `ghcide` to find it?

![image](https://user-images.githubusercontent.com/1951567/68991591-3d7d7d80-0858-11ea-98f9-58eeed775840.png)

**Comment by cocreature** [comment]
Does it work if you run `ghcide` in a terminal? Maybe emacs is invoking it from the wrong directory or something like that?

**Comment by jneira** [comment]
@tomjaguarpaw i am gonna close this one, feel free to reopen if you continue experiencing the issue
