### ISSUE TITLE
unknown symbol `_GLOBAL_OFFSET_TABLE_'

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/ghcide#201]
I'm attempting to use `ghcide` with GHC 8.4.4.  When running `ghcide` in a project directory I get the following error.  Does `ghcide` work with 8.4?  If not could this please be made clear in the README? If so, what am I doing wrong?

```
...
Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: /usr/lib/ghc/ghc-prim-0.5.2.0/HSghc-prim-0.5.2.0.o: unknown symbol `_GLOBAL_OFFSET_TABLE_'
ghcide: ghcide: unable to load package `ghc-prim-0.5.2.0'
```

**Comment by tomjaguarpaw** [comment]
Well, I get exactly the same error with 8.6.5 that I installed with ghcup, so that problem must be something else to do with my system.

**Comment by tomjaguarpaw** [comment]
(Maybe this is because I am on 32-bit?)

**Comment by tomjaguarpaw** [comment]
(Indeed on by 64-bit system `HS-ghc-prim-0.5.3` does not contain the symbol `_GLOBAL_OFFSET_TABLE`

**Comment by cocreature** [comment]
Not quite sure what is going wrong here. We don’t do anything special regarding `_GLOBAL_OFFSET_TABLE` so my guess is that maybe the boot libraries that are included in your bindist (`ghc-prim` in particular) might be compiled differently from `ghcide` somehow. E.g., maybe one is compiled with `-fno-pic` and one isn’t.

**Comment by jneira** [comment]
ghc-8.4.4 support is about to be dropped, @tomjaguarpaw feel free to reopen if this is reproduced in a newer version
