### ISSUE TITLE
Install using homebrew

### ISSUE THREAD

**Issue by alper** [haskell/ghcide#218]
Can I install this using homebrew?

**Comment by cocreature** [comment]
Right now, no. I don’t really know how homebrew packaging for Haskell packages works (I don’t use MacOS) but if someone wants to give it a shot, I’d be open to merging it or at least point to it in the readme depending on what exactly this entails.

**Comment by tjweir** [comment]
I have forked this repo with the goal of providing a Homebrew formula for ghcide.

**Comment by ndmitchell** [comment]
I think this providing prebuilt binaries would be a feature of https://github.com/haskell/ide, as per https://neilmitchell.blogspot.com/2020/01/one-haskell-ide-to-rule-them-all.html

**Comment by jneira** [comment]
So the prebuilt binaries for macos are already offered by haskell-language-server, and there is no plans to add to ghcide itself, @tjweir @alper do you still think that using homebrew (for hls or ghcide) would be useful?

**Comment by jneira** [comment]
closing in favour of https://github.com/haskell/haskell-language-server/issues/703

**Comment by tjweir** [comment]
> So the prebuilt binaries for macos are already offered by haskell-language-server, and there is no plans to add to ghcide itself, @tjweir @alper do you still think that using homebrew (for hls or ghcide) would be useful?

No reason for using homebrew now.  I am very sorry at my delay.
