### ISSUE TITLE
Update feature list in README

### ISSUE THREAD

**Issue by pepeiborra** [haskell/ghcide#324]
The current list of features is missing code lenses for type signatures, as well as a bunch of new code actions added recently, docs in hovers, etc.

**Comment by gdevanla** [comment]
Is this ticket still to be addresed in ghcide. I assume this kind of feature list will be made available in the HLS readme.

**Comment by jneira** [comment]
well, ghcide still has direct users. 
Maybe we could complete the list here and link hls readme to it.

**Comment by pepeiborra** [comment]
I don't think it's worth doing anymore, since we are recommending people to use HLS instead of exe:ghcide
