### ISSUE TITLE
The main module to load is ambiguous

### ISSUE THREAD

**Issue by wraithm** [haskell/ghcide#328]
Just running `stack exec ghcide` in a project that has many many packages fails.

```
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling stack","","* * * * * * * *","The main module to load is ambiguous. Candidates are: "<big list of stack targets>
```

Specifying a single target in `hie.yaml` and specifying the folder which strictly contains the files for that target works, however, I'd love to be able to use ghcide in our project that has many  packages in it...

Is there some simple way to load all of these targets automatically?

**Comment by googleson78** [comment]
I think this is not supported yet - #113

**Comment by stevemao** [comment]
@googleson78 is there any workaround?

**Comment by m4lvin** [comment]
With older versions of ghcide I had no problems with a multi-exec project. So a (probably terrible) workaround is `git checkout v0.0.4 && stack install` :smirk_cat:

**Comment by jneira** [comment]
@wraithm do you continue experiencing the issue with lastest ghcide?

**Comment by wraithm** [comment]
I am not! Everything seems to load fine afaict.
