### ISSUE TITLE
Qualified names in type insertion

### ISSUE THREAD

**Issue by ndmitchell** [haskell/ghcide#453]
I usually get unqualified names (which is good), but in this case I got qualified names. Probably should always unqualify the names here. I've no idea which version of Ghcide I'm using, so if this got fixed recently, please ignore. I've also no idea how to repo or if it will repo reliably.

![image](https://user-images.githubusercontent.com/1651197/75113225-d3892700-5643-11ea-8d28-503dfc542ac5.png)

**Comment by jneira** [comment]
I cant reproduce with lastest hls (so i guess ghcide would not do it too)

**Comment by pepeiborra** [comment]
This happens because GHC diagnostics and suggestions seem to elide module qualifiers. Not sure whether it's a GHC configuration setting or a bug.

**Comment by jneira** [comment]
I tested it in windows and ghc-8.8.3

**Comment by ndmitchell** [comment]
From reading https://hackage.haskell.org/package/ghc-8.10.1/docs/src/RdrName.html#line-275 and https://hackage.haskell.org/package/ghc-8.10.1/docs/src/Name.html#pprModulePrefix `Opt_SuppressModulePrefixes` looks like it might be relevant.

However, testing this code, it doesn't seem to reproduce, so closing.
