### ISSUE TITLE
Dependencies are being reported as hidden

### ISSUE THREAD

**Issue by Eugleo** [haskell/ghcide#470]
I have a relatively new and small project. I'm using cabal for dependency management, and in my cabal file I have these packages listed:
```
build-depends:
  base,
  aeson,
  bytestring,
  containers,
  crypt-sha512,
  directory,
  entropy,
  http-types,
  ini,
  lens,
  scotty,
  SHA,
  sqlite-simple,
  text,
  unix-time,
  utf8-string
```

Apart from `sqlite-simple`, which I had to install from a local directory, I've let cabal to install everything from hackage with `cabal build`. However, whenever I try to import anything from these libraries, ghcide fails with errors similar to this one:

```
  Could not load module ‘System.Entropy’
  It is a member of the hidden package ‘entropy-0.4.1.5’.
  You can run ‘:set -package entropy’ to expose it.
  (Note: this unloads all the modules in the current scope.)
```

I have ghc 8.8.3 on my path and I made sure to build and install ghcide with the same version of ghc. The output of `ghcide --version` is:

```
ghcide version: 0.1.0 (GHC: 8.8.3) (PATH: [...])
```

And `ghc --version` outputs:

```
The Glorious Glasgow Haskell Compilation System, version 8.8.3
```

So, that leaves me wondering where the problem might be.

**Comment by Eugleo** [comment]
I (think I) managed to resolve this issue by using an explicit `hie.yaml` file, which I rather randomly put together based on SO questions and other issues on `hie-bios` and related repos:

```yaml
cradle:
  cabal:
    component: "exe:request2"
```
However, that somehow brings more questions than it answers.

1. Why did this help? Shouldn't everything be automatically guessed from the project having a `.cabal` file and not having a `stack.yaml` file or something like that?
2. What is this _component_, and why does it begin with _exe_? Is this documented somewhere?

I fear that without understanding 1 and 2 I'll be helpless when something inadvertently breaks again in the future.

**Comment by ndmitchell** [comment]
Does your package have both a library and an executable? Or just an executable? If it's already a available and open source, can you link to it? (I'll answer the questions, but that answer lets me know whether to explain/write some docs, or raise a bug against another repo.)

**Comment by Eugleo** [comment]
Executable only, and unfortunately it's not a public project.

**Comment by ndmitchell** [comment]
Hmm, then the hie.yaml should be not required. If you run `ghcide` on the command line without it, what does it say? The information about components is at https://github.com/mpickering/hie-bios#explicit-configuration

**Comment by Eugleo** [comment]
Thanks for the link, I'll check it out. When I remove the `hie.yaml`, I get the following output from `ghcide`:

<img width="883" alt="Snímek obrazovky 2020-03-08 v 13 18 28" src="https://user-images.githubusercontent.com/21257632/76162577-524f8b00-613f-11ea-8bcf-f4ce93312a0a.png">

And then...

<img width="576" alt="Snímek obrazovky 2020-03-08 v 13 19 18" src="https://user-images.githubusercontent.com/21257632/76162588-6bf0d280-613f-11ea-8292-bf3ac863e887.png">

(I uploaded images to preserve the colors, it is easier to read this way)

**Comment by ndmitchell** [comment]
The docs are all at https://github.com/mpickering/hie-bios#explicit-configuration. I think this might be a hie-bios bug, so worth reporting at https://github.com/mpickering/hie-bios.

**Comment by jneira** [comment]
I think this should be fixed by the multi-component support, @Eugleo feel free to reopen if you continue experiencing the bug with lastest ghcide/hls
