### ISSUE TITLE
Completions are duplicated if imports are

### ISSUE THREAD

**Issue by ndmitchell** [haskell/ghcide#472]
![image](https://user-images.githubusercontent.com/1651197/76167458-b5044f00-615e-11ea-85d4-d2921b61f359.png)

Both these point at GHC.Util. Would be great to avoid generating them first, but a simple `nubOrd` on showing the completions might be worthwhile too. Root cause is that I am importing the module GHC.Util twice.

**Comment by jneira** [comment]
It is reproduced with lastest ghcide

**Comment by botal9** [comment]
Hi! I'd be happy to work on this issue.

**Comment by ndmitchell** [comment]
Thanks @botal9 - that would be great. There are three relevant modules - the first three of https://github.com/haskell/ghcide/search?q=completion. Not sure at what level to reduce it - probably best to write a test, and then experiment with where to remove the duplicate.
