### ISSUE TITLE
ghc-8.8.3 with cabal-new install , could not resolve deps

### ISSUE THREAD

**Issue by mimi1vx** [haskell/ghcide#476]
```
cabal new-install  ghcide.cabal -f"-ghc-lib"  -v                                         ✘ 130 master ✱
Reading available packages of hackage.haskell.org...
Using most recent state specified from most recent cabal update
index-state(hackage.haskell.org) = 2020-03-09T11:53:12Z
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ghcide-0.1.0 (user goal)
[__1] trying: ghcide:-ghc-lib
[__2] trying: ghc-8.6.5 (dependency of ghcide -ghc-lib)
[__3] next goal: base (dependency of ghcide)
[__3] rejecting: base-4.13.0.0/installed-4.1... (conflict: ghc => base<0 &&
==4.12.*)
[__3] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__3] fail (backjumping, conflict set: base, ghc, ghcide)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, ghcide, ghc, ghcide:ghc-lib
Try running with --minimize-conflict-set to improve the error message.
```

**Comment by cocreature** [comment]
Why are you trying to compile against `ghc-lib`? This is pretty much only useful if you have a custom build of `ghc-lib` outside of Haskell, e.g., we use this for DAML. You won’t be able to run this on Haskell projects.

**Comment by mimi1vx** [comment]
@cocreature `cabal new-install  ghcide.cabal -f"-ghc-lib"`  is against ghc-lib?

**Comment by cocreature** [comment]
Ah right, sorry I keep getting confused by `cabal`’s flag syntax.

I’m not really sure what is going wrong here. It looks like somehow you end up trying to build against GHC 8.6.5. Maybe try forcing it explicitly via something like `--constraint ghc==8.8.3` or something like that.

**Comment by mimi1vx** [comment]
hmm, maybe bug in Cabal / cabal-install. I have ghc-8.8.3 bootstraped by 8.6.5

` 
 ,("Project version","8.8.3")
 ,("Project Git commit id","d0bab2e3419e49cdbb1201d4650572b57f33420c")
 ,("Booter version","8.6.5")
`

**Comment by sebeaumont** [comment]
I've had no issues building with `ghc-8.8.3`  -- try blowing away `./dist-newstyle`
then try `cabal build`

**Comment by jrp2014** [comment]
Works for me with `cabal-install version 3.0.0.0, compiled using version 3.0.0.0 of the Cabal library` and `ghc 8.8.3` just Xiong a `cabal build`

**Comment by jneira** [comment]
@mimi1vx hi! have you the chance or trying the [workaround above](https://github.com/haskell/ghcide/issues/476#issuecomment-598785186)? does it reproduce with lastest ghcide?

**Comment by mimi1vx** [comment]
ah, sorry for late reply,

in the end problem was on my side :( and `ghcide` is working fine with ghc-8.10.2
