### ISSUE TITLE
Suggest open imports

### ISSUE THREAD

**Issue by ndmitchell** [haskell/ghcide#480]
The new suggested import hint is super cool. But I prefer to usually import things unqualified. Any way to encourage the hint to do that? Or should we suggest both? Or a preference (although I hate preferences)? Or look at the users existing module imports and infer a preference?

**Comment by pepeiborra** [comment]
It should suggest a qualified import only when the thing is qualified. Screenshot or it didn’t happen.

**Comment by ndmitchell** [comment]
Sorry, the bug report is super confusing.

Given a use of `isUpper` it suggests `import Data.Char(isUpper)`. I'd like it to suggest `import Data.Char` in most cases. I'm using the word unqualified completely wrong above... Unconstrained imports? Open imports?

**Comment by pepeiborra** [comment]
I use the terms explicit/implicit imports. 

Explicit imports are the norm in recent languages including Purescript, Elm, and I think Rust as well? Most Haskellers have adopted this trend too, some people go as far as to use package imports. With IDE automation, I don’t see any reason to prefer implicit imports.

**Comment by jneira** [comment]
> I don’t see any reason to prefer implicit imports.

Well there are codebases that use implicit exports by default, at least for the more common/used modules. If you uses a lot of definitions and it has no name clashes it can be handy (but less safe).

But if you want honour the code style of such existing code base you have no other option (but change the entire codebase :smile:)

**Comment by fendor** [comment]
Yeah, hie suggests both, which admittedly causes more clutter in code actions.

**Comment by ndmitchell** [comment]
I don't use explicit/implicit because I've spent way too much time on the implicit prelude import, where implicit means something different. Shame there isn't a better name.

I don't like the implicit style because I spend all day adding imports and removing them as I refactor. That gives lots of meaningless diff noise. Languages like Rust have implicit imports of types, and then most functions hang off types - that's a perfectly reasonable way to go - but it's very different to Haskell with implicit imports.

**Comment by ocharles** [comment]
Just to give some more information, I prefer the current behavior. Open imports may be convenient for diffs, but in code reviews I just skip over imports entirely anyway and don't really care. But open imports have other implications that make me discourage them (hard to discover symbols when reading code outside an editor, easier to introduce conflicting symbols, etc)

**Comment by pepeiborra** [comment]
I'm not against suggesting both, probably the most democratic option.

Some things like `lift` already generate dozens suggestions from all the modules reexporting them anyway.

**Comment by ndmitchell** [comment]
I wondered if it was possible to look at what other modules in the graph use. E.g. if I often do `import Data.ByteString as BS` to get `isUpper` then that's probably what I want in this module too.
