### ISSUE TITLE
Call to mask cradle initialisation is probably ineffective

### ISSUE THREAD

**Issue by mpickering** [haskell/ghcide#494]
Pepe inserted a call to mask the cradle initialisation recently but I don't think it will work as expected because the cradle initialisation will call functions from `System.Process` which I think are interruptible. 

https://github.com/digital-asset/ghcide/blob/master/exe/Rules.hs#L80

On the multi-cradle branch I have certainly observed async exceptions bringing down this code path, which were "fixed" by using `uninterruptibleMask` rather than `mask`.

Can you comment on what the right fix for this is @ndmitchell ?

cc @pepeiborra

**Comment by ndmitchell** [comment]
My experience is using mask is nearly always wrong, and using mask or any related functions correctly is nearly impossible. I'm somewhat disheartened with async exceptions entirely!

**Comment by pepeiborra** [comment]
Have you run into the error described [here](https://github.com/digital-asset/ghcide/pull/471#issuecomment-596231636) after my change? 

The argument against `uninterruptibleMask` is that it will probably make it impossible to kill ghcide. So what do you do if the wrong cradle is picked up and `stack` starts compiling the universe?

**Comment by mpickering** [comment]
Yes it is exactly that issue that led me to investigate this.

**Comment by mpickering** [comment]
Using `mask` to try to fix the hadrian error that Pepe mentions above is not really the correct fix. The error arises because hadrian does not like being invoked in quite succession, it is already not called concurrently because there is a lock guarding this part of the code. The `uninterruptibleMask` call stops it being called in close succession as the first thread is never killed. 

So I can think of two possible ways of fixing this:

1. Create a specific thread where we do cradle initialisation, which is never killed. 
2. Make sure there is at least 0.1s between calls to initialise a cradle, so the cradle is not called and killed in quick succession.

**Comment by ndmitchell** [comment]
The former of those seems most appropriate. We'd also want things to wait on a previously started but not yet finished cradle init rather than starting a new one.

**Comment by pepeiborra** [comment]
Worth considered a third option, fix this in hie-bios by intercepting asyncronous exceptions and waiting for clean up before rethrowing

**Comment by ndmitchell** [comment]
Even if hie-bios could intercept the exception and roll back everything, I don't think we'd want to - from ghcide it makes sense to let hie-bios actions that have already started run to completion since we know the chances of them being required is super high and the cost of aborting midway through is also high.

**Comment by mpickering** [comment]
What clean up could be observed? 

I don't think calling an external process many times is desirable anyway as they can behave unpredictable when killed, as we have observed with hadrian.

**Comment by pepeiborra** [comment]
Clean up in this case is `waitForProcess`.

**Comment by mpickering** [comment]
There is a fix for this in #522

**Comment by jneira** [comment]
Fixed by #522
