### ISSUE TITLE
Allow files to be excluded from processing via ghcide.

### ISSUE THREAD

**Issue by AndreasPK** [haskell/ghcide#501]
I'm using VSCode with the ghcide plugin.

When I setup core/stg dump files to be highlighted as haskell this also triggers ghcide to try to process them which obviously fails.

I wondered if there is a way to avoid this as these non-errors do clutter the "Problems" list a bit.

**Comment by fendor** [comment]
You can ignore paths when ghcide starts to support the `none`-cradle. Issue #258.

**Comment by mpickering** [comment]
Would the correct solution be to add a language `Haskell (Core)`, which syntax highlights core files? The fact the Haskell syntax highlighting works somewhat seems like an accident.

**Comment by jneira** [comment]
@AndreasPK The none cradle is already supported and you can use it to exclude those files
