### ISSUE TITLE
Show where the definition was imported from

### ISSUE THREAD

**Issue by domenkozar** [haskell/ghcide#523]
I often wonder where is something imported from. For an example `dimap` could come from any of the imports since I know I don't import any profunctor packages.

Proposal: `Defined in <module>, imported from <module>`

**Comment by mpickering** [comment]
What do you want to do with this information? It seems possible your issue may be solved more directly.

**Comment by domenkozar** [comment]
I'd like to import it in another file. 

While there is a code action to add an import for a binding, it usually lists quite a bunch of possibilities.

One option would be to group import suggestions by existing and available imports in the project.

**Comment by ndmitchell** [comment]
What I often want to do is copy a fragment of code from one module, paste it in another, and "drag" all the imports that were required across. E.g. if one module has `import Data.HashMap as HM` and I copy the expression `HM.filter` then I want the import moving to the new module (or even better, adjusting if I have `Data.HashMap as HM2` in that file. Knowing that the `foo` keyword comes via a particular import is one way to do that slightly manually.

**Comment by jneira** [comment]
Afaict the info on hover already include the `Defined in <Module>` in ghcide/hls (not sure what pr did the change)
