### ISSUE TITLE
ghcide-nix support for ghc 8.8 ?

### ISSUE THREAD

**Issue by zeta-00** [haskell/ghcide#532]
hello there, i'm contributing to the ghc compiler, but the ghc.nix instructions say ghcide does not support ghc version 8.8 yet, i was wondering when you expect this issue to be fixed ? thanks for taking the time to read this issue

**Comment by ndmitchell** [comment]
We already support GHC 8.8. We're currently working on 8.10.

**Comment by zeta-00** [comment]
@ndmitchell , oh ok, that's good to know, this link for ghc.nix says it's currently unavailable: https://github.com/alpmestan/ghc.nix#using-ghcide-%EF%B8%8F-currently-unavailable , i'm contributing to ghc, so i really need ghcide to aid me in the devolopment of ghc.

**Comment by fendor** [comment]
You can still use ghcide if you build it from source. It may take like half an hour, but it is definitely doable.
As I read the issues, there is nothing that ghcide can do to aid ghc.nix.

**Comment by zeta-00** [comment]
@fendor , ok sounds good, now that i know ghcide supports ghc version 8.8, i'll go back to the ghc.nix devs to see what progress they've made in getting ghcide working. i'm upgrading all my stuff from ghc 8.6 to 8.8, so i'm guessing some things will break. i am finally able to get nix-shell working in emacs(lorri+direnv+emacs-direnv) using a workaround, so i finally got ghcide(with ghcWithHoogle) working in that setup. if i have to build ghcide manually, i'll do it, but, i might wait until this gets fixed. also, i just upgraded to nixos 20.03, so i'm trying to get things up and running with that channel.

anyways,
thanks for the update,
(this virus has really slowed things down)

**Comment by domenkozar** [comment]
@zeta-00 you can use https://github.com/cachix/ghcide-nix/pull/32, but to get the binaries you'll need to wait another day or three.

**Comment by zeta-00** [comment]
@domenkozar , sounds good, thanks for the update

**Comment by fiadliel** [comment]
With ghcide + haskell.nix + ghc 8.8, I'm getting

>   ghcide compiled against GHC 8.8.3 but currently using an unknown version of GHC . This is
>   unsupported, ghcide must be compiled with the same GHC version as the project.

... because ghc is broken in the package database. With `reinstallableLibGhc`, ghc just isn't in the package database. Either scenario breaks the compatibility check.

I guess in the long term, hopefully the package database stuff can be fixed, but we probably also need an opt-out flag from this check.

**Comment by mpickering** [comment]
@fiadliel See #534, seems like a different issue.

**Comment by andys8** [comment]
Merged

**Comment by jneira** [comment]
ghcide has already support for ghc-8.8
