### ISSUE TITLE
error: attribute 'ghcide-ghc883' missing

### ISSUE THREAD

**Issue by zeta-00** [haskell/ghcide#553]
i upgraded my ghc config in my shell.nix file from ghc865 to ghc883, but when i set my ghcide-nix installation to ghc883 it threw an error? does ghcide-nix not support ghc version 883 yet?

# ghcide-nix installation:
(import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc883

**Comment by fendor** [comment]
It seems like it is not supported? https://github.com/cachix/ghcide-nix/issues/3

**Comment by andys8** [comment]
There is https://github.com/cachix/ghcide-nix/pull/32/commits/7932bfbaf98b995a11d9b19a757584df3821a64e

**Comment by jneira** [comment]
Closed by https://github.com/cachix/ghcide-nix/commit/7932bfbaf98b995a11d9b19a757584df3821a64e
