### ISSUE TITLE
GHC version check appears to not be correct

### ISSUE THREAD

**Issue by mpickering** [haskell/ghcide#559]
Reported by @jneira 

```
Error while checking GHC version: "D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc: readCreateProcess: does not exist (No such file or directory)"
```
Reported at the bottom of this comment with no further details.

https://github.com/mpickering/ghcide/pull/32#issuecomment-626235387

@pepeiborra

**Comment by pepeiborra** [comment]
This is the expected behaviour if ghc-check cannot figure out the runtime version of GHC: print the underlying exception and continue the execution.

Would it help if we change the print line to make this explicit? E.g.
```
Warning: unable to validate that ghcide was compiled with the same version of GHC: ...
```

**Comment by pepeiborra** [comment]
I have opened a separate issue in the ghc-check tracker to investigate why the logic to guess the ghc binary location didn't work in this case, as I have not tested it with stack:
https://github.com/pepeiborra/ghc-check/issues/2

**Comment by jneira** [comment]
Just in case the ghc executables is not in `D:\\\\bin\\\\stack\\\\x86_64-windows\\\\ghc-8.8.3\\\\lib\\bin\\ghc` but in `D:\bin\stack\x86_64-windows\ghc-8.8.3\bin\ghc`
I ws not using stack but cabal (in ghc codebase using the script that builds with cabal), it turns out that i use the ghc's installed by stack for cabal too.

**Comment by pepeiborra** [comment]
Thanks, turns out the GHC installation layout is different in Windows. I'll update the logic in ghc-check

**Comment by uzhas-sovka** [comment]
I copied all contents of one folder to another. Stupid, but it worked.

**Comment by jneira** [comment]
Afaik `ghc-check` already has the fix for that
