### ISSUE TITLE
Crash while typing import

### ISSUE THREAD

**Issue by pepeiborra** [haskell/ghcide#570]
Action: paste or type an import statement
Behavior: ghcide stops responding to editor requests. The ghcide log window shows:

```
ghcide: importLine does not have the expected structure: import           Strats.Cloud.Types.Se
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Plugin/CodeAction.hs:550:7 in ghcide-0.1.0-GPErgG7kX2FB5cNzVYvUCT:Development.IDE.Plugin.CodeAction
```

**Comment by ndmitchell** [comment]
Ouch - we definitely shouldn't be calling error there. We probably need a two-pronged fix of not calling error there, and also a more general approach of shoving a catch around code actions etc. so they don't take out the IDE.

**Comment by jneira** [comment]
I cant reproduce with lastest ghcide. is the @ndmitchell suggestion still needed?

**Comment by pepeiborra** [comment]
Yes

**Comment by jneira** [comment]
Ok, so afaiu it would be an generic improvement in error handling (as the original bug is not reproduced anymore)

**Comment by pepeiborra** [comment]
Closing this issue as the particular `error` call that caused this crash no longer exists, and the general approach is implemented already in `hls-plugin-api`, so all we need to do is split and move our code actions to HLS providers, and there exist tickets for that already
