### ISSUE TITLE
.hi file checks are expensive

### ISSUE THREAD

**Issue by ndmitchell** [haskell/ghcide#583]
Looking at some recordings of which operations are executed during a hover request on the Shake repo (100+ real files), there are approx 2200 rules involved. Classifying those into ones that do some work (not literally zero work) there are 375. It is definitely possible to optimise those that don't do anything to have nearly zero cost, but once I do that (ideally with benchmarks...) we'll be left with those that have some cost. They break down into:

* 1 x GetFilesOfInterest - happy to keep this one around, it's literally one, so seems fine.
* 125 x GetModificationTime in the workspace - I believe we should switch these to using the VSCode watching for them. I think that's feasible.
* 124 * GetModificationTime + 124 * GetFileExists on every .hi file in `C:\\Users\\ndmit_000\\AppData\\Local\\ghcide\\44a1c205801868d589ca26f9c844cc8d55a566b8`. These are outside the workspace so don't benefit from being remembered by VS Code. My guess is that we assume these files only change outside our control when we're not running? If so, that knowledge should be lifted into the build system, and we shouldn't tell Shake to keep polling for them.

**Comment by pepeiborra** [comment]
For `GetModificationTime` to rely on the lsp notification events, is #325 what you have in mind? I implemented it in PR #373 a while ago but we didn't end up merging it due to unclear perf benefits.

**Comment by mpickering** [comment]
What exactly is expensive about the check? This hasn't been something which has showed up on any profiles I have done as a performance bottleneck.

**Comment by pepeiborra** [comment]
For interface files, the `GetModificationTime` checks are needed  for staleness checking, and to reload them when they are regenerated. It should be easy to remove the `GetFileExists` dependency.

**Comment by ndmitchell** [comment]
@pepeiborra exactly right. My guess is that the unclear perf was down to Shake not taking advantage of the knowledge it provides. The way DoesFileExist clearing is wired in also doesn't give Shake much info, but if we change that (which I'm looking at) then GetModificationTime probably would show a benefit.

@mpickering we end up doing 1 modtime and 1 existence check per file on every hover. For GHC, I imagine that's 1000 disk operations per hover. I would have imagined you wanted to get the number of disk ops on a hover down to 0.

**Comment by ndmitchell** [comment]
@pepeiborra aren't we the ones that regenerate them? Thus we don't need to check the disk to see if we did it - we have the information to hand.

**Comment by pepeiborra** [comment]
> @pepeiborra aren't we the ones that regenerate them? Thus we don't need to check the disk to see if we did it - we have the information to hand.

Right, I imagine we need a new rule key `HiFileModificationTime` and a helper function to directly update its value into the store, like we do for `GetFileExists`, is that it?

**Comment by ndmitchell** [comment]
Yep, something of that nature. I'm looking at how we do the does file exist optimisation now and trying to make it more "first class" so will take a look at this after.

**Comment by pepeiborra** [comment]
Are you still planning to make any changes around this area Neil? If not, I'd like to start pushing it forward

**Comment by ndmitchell** [comment]
I'm not looking at anything for now. I have a vague plan once everything from Matt's branches is landed to take a holistic look at the Shake abstraction API and adjust it to deal with being push rather than pull, but the plan is vague, and the timeline is at least a month or two out. The existing stuff for get modification time watching looked quite plausible, so taking the same approach would be great.

**Comment by jneira** [comment]
It seems this was resolved by #589. Feel free to reopen if it is not the case
