### ISSUE TITLE
repeated builds in emacs

### ISSUE THREAD

**Issue by adamConnerSax** [haskell/ghcide#604]
Using ghcide 0.2 from command line or emacs, I get a weird behavior where things start rebuilding the same few dependencies for, I think, every file in the project?

I get a "Consulting the cradle for ..." and then "resolving dependencies" and then it builds them and then that happens again for lots of files, maybe all of them.  

I did have a (one-line, for cabal) hie.yaml.  Same behavior after deleting that.

**Comment by mpickering** [comment]
Impossible to make any progress without any reproduction or log output.

**Comment by jneira** [comment]
@adamConnerSax i think some improvements for emacs and file handling was added (#831), could you try last ghcide version to checkit that is reproduced (or even better switch to haskell-langiage-server)

**Comment by adamConnerSax** [comment]
Swicthed to haskell-language-server and this behavior did indeed cease.  Still crashes a bunch from emacs but I can't pin it down to anything small and reproducible...
