### ISSUE TITLE
ghcide does not recognize the DerivingVia extension

### ISSUE THREAD

**Issue by poscat0x04** [haskell/ghcide#631]
It does not show up during completion.

**Comment by poscat0x04** [comment]
It's not just `DerivingVia`, a couple more extensions, such as `QuasiQuotes`, also suffer from this problem.

**Comment by gdevanla** [comment]
Can someone elaborate a little more on what the behavior is supposed to be?

**Comment by jneira** [comment]
maybe @ndmitchell could help with

**Comment by jneira** [comment]
@gdevanla feel free to go into #haskell-ide-engine room in freenode irc (you can use https://kiwiirc.com/nextclient/ for example) and ask for hls, ghcide, haskell-lsp, etc topics. Not always is active but hopefully someone will answer sooner or later.

**Comment by ndmitchell** [comment]
It works for completions for me. 

![image](https://user-images.githubusercontent.com/1651197/100008866-e775db00-2dc5-11eb-9c0f-d7ae7f48bb03.png)

Windows, VS Code, I guess the latest HLS? (I don't even know how to tell...)

**Comment by gdevanla** [comment]
I am not able to see any completions on extensions using latest HLS and Emacs.

**Comment by gdevanla** [comment]
I feel like we could move `{-# language` and `{-#options_ghc` and any `{-#` completions out of cachedCompletions functions defined here.  https://github.com/haskell/ghcide/blob/e24a744a06ee8807fd0a2c6b2db3f4eed0738372/src/Development/IDE/Plugin/Completions/Logic.hs#L564-L569

By moving it our into its own rule( outside NonLocalCompletions) we can show this completions, without encountering the parser error I am observing now. Is that approach acceptable?  Are there any negative implication to that approach I should be aware of? If not, I will attempt to make that change.

**Comment by pepeiborra** [comment]
Yes, this goes in the right direction. My preference would be to decompose the completions code into multiple providers, which is exactly what the plugin model in haskell-language-server does. 

Given that there is already a [plugin to suggest pragmas](https://github.com/haskell/haskell-language-server/blob/master/plugins/default/src/Ide/Plugin/Pragmas.hs) in HLS, which at the moment it only provides code actions, I would support moving the completions code to that plugin, and at the same time take the chance to get rid of the code action in ghcide that does the same thing as reported in #380.

**Comment by gdevanla** [comment]
Thanks @pepeiborra  . The plugin seems to be the perfect place to add this change. I will move the functionality there.

But, can you clarify how this is related to #380. I may be missing some context here.

**Comment by pepeiborra** [comment]
Oops, I meant github.com/haskell/haskell-language-server/issues/380

**Comment by poscat0x04** [comment]
I'm pretty sure this issue no longer exists in version 0.6.0.0.

**Comment by gdevanla** [comment]
I have not been able to get this working with latest (master) hls/ghcide on Emacs. I need to dig deeper to see if this is an Emacs issue. Whenever, I my cursor is inside the bounds of this text {-# #-}, I do not see any requests for 'textdocument/CodeCompletion' going out to the server at least in Emacs. If others, feel this is only an Emacs issue than we can close this ticket.

For now, I am trying to reproduce this outside any editor. The HLS plugin currently does not have any tests, and many tests in HLS seemed to be commented out.

**Comment by gdevanla** [comment]
I fixed this issue with Emacs [here](https://github.com/emacs-lsp/lsp-haskell/commit/592e883026288677f4042333b51efc7a40b9a68a).  I think this issue can be closed.

**Comment by poscat0x04** [comment]
closing
