### ISSUE TITLE
Problem with ghcide, NixOS, cabal and cradle

### ISSUE THREAD

**Issue by bratfizyk** [haskell/ghcide#636]
I've been trying to migrate my development from Ubuntu to NixOS. No issues with my project and ghcide on Ubuntu. However, when I build my project on NixOS using "cabal new-build", I get an error about missing zlib:

```
Configuring library for zlib-0.6.2.1..
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing (or bad) C library: z
```

I fixed that by creating nix files with all the dependencies and building my project via nix-shell. However, my ghcide cradle is still defined as:

`cradle: {cabal: {component: "MyProject"}}`

Which fails for the same reason - unavailable zlib. Is there a way to instruct the cradle to go via nix-shell ?

**Comment by pepeiborra** [comment]
This is editor specific. For Emacs I would use direnv, in VSCode I've had success with https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector

**Comment by bratfizyk** [comment]
Thanks, I use VSCode, but wasn't successful enough with the extension you've mentioned. I'll keep on trying though.

**Comment by poscat0x04** [comment]
You could just open vscode inside `nix-shell` using its command-line tool `code`

**Comment by bratfizyk** [comment]
As I'm pretty new to nix(OS), can you tell me how to do this ? I've tried both "nix-shell code" and "nix-shell ~/.nix-profile/bin/code" without a much success.

**Comment by fendor** [comment]
@bratfizyk Personally, I have a `shell.nix` or `default.nix` in my project that declares the necessary dependencies.
Then I drop into that shell via `nix-shell`. After that you have a shell where your dependencies are available. You can just type `code .` or `codium .` and it should work.

**Comment by bratfizyk** [comment]
@fendor Thanks, that sounds much clearer to me now. I made one step forward, but still no good.

Here's my shell.nix:
```
{ nixpkgs ? import ./pkgs.nix {} }:
let
  inherit (nixpkgs) pkgs;
  inherit (pkgs) haskellPackages;

  haskellDeps = ps: with ps; [
    aeson base bytestring Cabal cassava containers dates directory
    esqueleto http-api-data lens lucid monad-logger mtl persistent
    persistent-sqlite persistent-template regex-posix resourcet servant
    servant-lucid servant-server text time transformers unliftio-core
    utf8-string vector wai warp wreq
  ];

  ghc = pkgs.haskell.packages.ghc865.ghcWithPackages haskellDeps;

  nixPackages = [
    ghc
  ];
in
pkgs.stdenv.mkDerivation {
  name = "snadbox-haskell-workspace";
  buildInputs = nixPackages;
}
```

What I get from ghcide is error: "Cannot satisfy -package-id Cabal-2.4.0.1". I get the same error in both cases, e.g.
* while running VSCode with nix-env-selector extension pointing to my shell.nix.
* while running code after executing "nix-shell shell.nix".

I guess that means something's wrong with my shell.nix file. Any obvious mistakes there ?

Also, I've got slightly different files defined with cabal2nix ("default.nix"):

```
{ mkDerivation, aeson, base, bytestring, Cabal, cassava, containers
, dates, directory, esqueleto, http-api-data, lens, lucid
, monad-logger, mtl, persistent, persistent-sqlite
, persistent-template, regex-posix, resourcet, servant
, servant-lucid, servant-server, stdenv, text, time, transformers
, unliftio-core, utf8-string, vector, wai, warp, wreq
}:
mkDerivation {
  pname = "FortPolio";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    aeson base bytestring Cabal cassava containers dates directory
    esqueleto http-api-data lens lucid monad-logger mtl persistent
    persistent-sqlite persistent-template regex-posix resourcet servant
    servant-lucid servant-server text time transformers unliftio-core
    utf8-string vector wai warp wreq
  ];
  license = "MIT";
  hydraPlatforms = stdenv.lib.platforms.none;
}
```

I use it via another file called "release.nix"

```
let
    pkgs = import ./pkgs.nix { };
in
    pkgs.haskellPackages.callPackage ./default.nix { }
```

(pkgs.nix is just a pinned nixos-20.03). This file causes the entire project to build just fine when used via: nix-build release.nix. However, doesn't work for ghcide.

**Comment by bratfizyk** [comment]
After some time researching the problem I think it can be summarized as follows:
* all fine when using "nix-build ./release,nix" - it builds fine and outputs a binary
* executing "nix-shell ./release.nix" and then "cabal new-build" doesn't work.

Is there anything else that nix-build does and nix-shell doesn't do ?

**Comment by bratfizyk** [comment]
Update from my side: I've just migrated from nixos-20.03 to nixos-20.09, which contains ghcide version 0.3.0. Migrating to the newer version solved my problem and I can now use ghcide in VS Code following the hints you had provided here. Many thanks for the help.
