### ISSUE TITLE
"insert type signature" does not respect qualified imports

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/ghcide#652]
For example, inserting a type signature for the expression `test` below causes an error because `test :: Ratio Integer` is inserted instead of `test :: Real.Ratio Integer`.

```haskell
import GHC.Real ((%))
import qualified GHC.Real as Real

test = 4 % 5
```

I'm using ghcide version: 0.2.0 with GHC: 8.6.5.

**Comment by codygman** [comment]
I was literally coming here to post this :laughing: 

It's not too bad, since the next quickfix will be the qualified version, but it is enough to break my "flow".

Since our codebase at work uses qualified imports _everywhere_, that means ghcide is less amazing of an experience (though still amazing! :smile:).

I might be interested in taking a stab at this as well if anyone can provide some breadcrumbs or direction.

**Comment by runeksvendsen** [comment]
> I was literally coming here to post this 😆

Great minds think alike 😉

By the way, I just thought of something that may need to be taken into consideration when fixing this issue. In essence: what to do when the inferred type signature contains types that are not in scope in the current module? Let's say we have the following block of code:

```haskell
import Control.Concurrent (myThreadId)

someThreadId = myThreadId
```

Inserting a type signature will insert `someThreadId :: IO ThreadId`, which will cause an error since `ThreadId` is not in scope. Generally speaking, it's entirely possible for types in the inferred type signature to be out-of-scope, and I think -- while fixing this issue -- we should decide how this should be handled.

Also, what if an inferred type is not exported by any of the current dependencies, so that a new dependency needs to be added in the case the user wants to insert a type signature?  
I don't have an example at hand, but it's possible that a module exports a value whose type signature includes a type constructor that isn't exported by the library in question, thus requiring that a new dependency is added -- which I don't think ghcide is capable of (yet).

I think the best solution would be to make it configurable, and ignore the missing dependency-case until ghcide knows how to manage dependencies.

**Comment by runeksvendsen** [comment]
Related issue: #726 

By the way, if this is a good first issue then I'd love a couple of pointers to get started hacking on ghcide.

**Comment by ndmitchell** [comment]
I'm not sure this is a good first issue... But really, being motivated and caring about something makes something a good first issue for you, so I'll give you a few hints - but I'm not fully sure what the answer looks like.

* https://github.com/digital-asset/ghcide/blob/826e886adac32378cb8a9f1ad735ca9234806eab/src/Development/IDE/Plugin/CodeAction.hs#L93-L131 seems to be the part which inserts type signatures and suggests them. I found that by searching for "insert type signature" in this repo.
* https://github.com/digital-asset/ghcide/blob/826e886adac32378cb8a9f1ad735ca9234806eab/src/Development/IDE/Plugin/CodeAction.hs#L490-L512 seems to be the bit that generates the textual suggestion.

It seems we are processing the text from a GHC warning. So does the GHC warning get the qualification right? If not, that might be one that is better fixing upstream in GHC. If you want to hack it locally in Ghcide, then you might need to parse the type signature, and go through type by type trying to resolve it. That probably needs a current environment. Fixing it upstream in GHC is the "best" way to solve it (or even just turning it into a GHC bug is a good first step), while fixing it in Ghcide has a much shorter turnaround to getting a working result.

**Comment by runeksvendsen** [comment]
Thank you Neil.

If I do the following:

1. `stack --resolver=lts-14.0 new qualified-sig`
2. `cd qualified-sig`
3. Add 

```
ghc-options:
  - -Wall
```

to `package.yaml`

4. Add the code snippet

```haskell
import GHC.Real ((%))
import qualified GHC.Real as Real

test = 4 % 5
```

to `src/Lib.hs`

5. Run `stack build`

then GHC correctly outputs the qualified name in a warning:

```
/Users/runesvendsen/tmp/qualified-sig/src/Lib.hs:9:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature:
      test :: Real.Ratio Integer
  |
9 | test = 4 % 5
  | ^^^^
```

However, opening `src/Lib.hs` in VSCode and hovering over `test`, the popup reads `Top-level binding with no type signature: test :: Ratio Integer` (incorrect/unqualified name).

The only way I can get GHC to output without a qualification is if `Ratio` is actually in scope (thus making this output correct). So I wonder if, internally in ghcide, there are different values in scope than what is specified in the source file... Ie. is ghcide adding any imports to a source file when processing it (perhaps to aid autocompletion)?

**Comment by ndmitchell** [comment]
So GHC gets it right, Ghcide gets it wrong - great find! Possible reasons:

* We get the right message, then preprocess it textually to strip the information. I linked to the place we do the preprocessing. Perhaps remove most of that and see what happens.
* We have more modules in scope. Quite possible. Would be a shame.
* We set some pretty print without qualification flag somewhere.
* We do our own pretty printing of errors (we do, see the errors module) and we aren't passing some pretty printing flag GHC does.

Would be great to find out which it was. The one you identify is probably the hardest to fix, but the others probably aren't too hard.

**Comment by runeksvendsen** [comment]
I finally had some more time/motivation to look at this issue.

I grepped the code base for case-insensitive "qualif" and found the following suspicious line: https://github.com/haskell/ghcide/blob/1bb4c49fdacf969a0f18b032859480ba00515107/src/Development/IDE/Spans/Common.hs#L48.


[`neverQualify`](https://hackage.haskell.org/package/ghc-8.10.1/docs/Outputable.html#v:neverQualify) is a GHC flag -- although its documentation isn't very elaborate on its meaning. So -- it appears -- `Development.IDE.Spans.Common.showName` prints unqualified names only. I *assume* this related to the user's qualifications (e.g. the `B` in `import Blah as B`) as opposed to full qualifications (which I believe are always valid, regardless of the user's qualifications).

`showName` is used by `Development.IDE.Spans.AtPoint.atPoint` to get the name at a position. `atPoint` is used by `Development.IDE.Core.Rules.getAtPoint`, which is used to display information on hover: https://github.com/haskell/ghcide/blob/62f4d0644a3db022a49f582e2ad620c0aa6d241a/src/Development/IDE/LSP/HoverDefinition.hs#L34

I'm not sure where to go from here. I'm not 100% sure this is the culprit (I have yet to connect `showName` with `Development.IDE.Plugin.CodeAction.suggestSignature`), but it seems very likely. I assume there's a good reason all names are printed without qualification, and that I would break a lot of things simply by changing/removing this flag.

**Comment by runeksvendsen** [comment]
**Update:** changing `neverQuality` to `reallyAlwaysQualify` at https://github.com/haskell/ghcide/blob/1bb4c49fdacf969a0f18b032859480ba00515107/src/Development/IDE/Spans/Common.hs#L48 does not change the suggested type. Only the popup that appears when hovering over the definition changes from:

```
test :: Ratio Integer
```

to

```
fake_uid:Main.test :: base-4.13.0.0:GHC.Real.Ratio
  integer-gmp-1.0.2.0:GHC.Integer.Type.Integer
```
