### ISSUE TITLE
what can I do now? I have ghcide running. Documentation needed!

### ISSUE THREAD

**Issue by andrewufrank** [haskell/ghcide#658]
I have ghcide running for my project (in VScode) using ghc 8.8.3. It shows errors as I type. Good. 

But how to I go from the error message to the line in the code to fix it? I cannot find information how this is done.
What are other functions ghcide provides? Insert type? How? Go to the definition? How? 

Could somebody point to where I find this information, and perhaps add it to the READ ME - it is very detailed on how to install on different IDEs, but short on what you can do once ghcide is installed. 

I am willing to learn, perhaps even to write documentation...

**Comment by ndmitchell** [comment]
I think such information should live on the Haskell Language Server page - https://github.com/haskell/haskell-language-server. As to the questions you ask above, they are all VS Code specific. Goto definition is at https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition. Insert type isn't provided, unless a link pops up above the line, in which case just click it. Goto error is discussed at https://github.com/Microsoft/vscode/issues/52391

I opened https://github.com/haskell/haskell-language-server/issues/491 to track these points, so closing this one.
