### ISSUE TITLE
[Error] internal error - GetModIfaceFromDisk of file of interest

### ISSUE THREAD

**Issue by Kleidukos** [haskell/ghcide#664]
I don't really know if that is an issue for the maintainer team to fix or if it's trying to tell me something, but here is the full version:

```
[Error] internal error - GetModIfaceFromDisk of file of interest CallStack
(from HasCallStack): error, called at src/Development/IDE/Core/Rules.hs:643:17
in ghcide-0.2.0-HMC3T0PbkEC6PyhYSkuumc:Development.IDE.Core.Rules  
```

**Comment by pepeiborra** [comment]
I thought I had fixed this issue in #623 but clearly did not. What version of ghcide are you using?

**Comment by Kleidukos** [comment]
Hi @pepeiborra!
Here's the version:
```
ghcide version: 0.2.0 (GHC: 8.6.5) (PATH: /home/hecate/.local/bin/ghcide-8.6.5) (GIT hash: 8de10e9474898b43c66581f40fe0eea6741a286b)
``

**Comment by pepeiborra** [comment]
Thanks, that was after the fix landed. Hmm, I don't see how this could happen anymore, we must have a race condition of some sort. Do you remember what triggered it, or even better, do you have a repro?

**Comment by Kleidukos** [comment]
@pepeiborra Unfortunately it's on a company repo so I can't share it. IIRC, I sent a "hover" message from my editor.

**Comment by pepeiborra** [comment]
I believe this is fixed
