### ISSUE TITLE
poor advice from ghcide

### ISSUE THREAD

**Issue by andrewufrank** [haskell/ghcide#668]
I got from ghcide the advice 
perhaps you could include `-- :set -package Cabal` in your `.ghci` file, which I naively followed. it did not help me to start my main.... (;-) 
is this a bug or are there cases where it is reasonable to include the `setup.hs`?

**Comment by cocreature** [comment]
Can you add some more details please?

**Comment by andrewufrank** [comment]
i hit return to quickly, now it is edited and hopefully clear enough.

**Comment by sureyeaah** [comment]
@andrewufrank can you explain more?

**Comment by andrewufrank** [comment]
sorry, i am not currently working on this project and cannot reconstruct the situation; I will reopen, if it appears again in the future.
