### ISSUE TITLE
Access violation when running ghcide on my codebase

### ISSUE THREAD

**Issue by LukaHorvat** [haskell/ghcide#669]
I'm on Windows, running ghcide on a project I can't really share. I pulled from latest master today, and am using GHC 8.6.5.

```
ghcide --version
ghcide version: 0.2.0 (GHC: 8.6.5) (PATH: C:\Users\Luka\AppData\Roaming\local\bin\ghcide.exe) (GIT hash: 21161389842a3141f82c82a6757d6eadfb264e8b)
```

When running `ghcide` inside of my stack project I get a crash ending with

```
File:     C:\project\Setup.hs
Hidden:   no
Range:    1:7-1:26
Source:   not found
Severity: DsError
Message:
  Could not load module `Distribution.Simple'
  It is a member of the hidden package `Cabal-2.4.1.0'.
  You can run `:set -package Cabal' to expose it.
  (Note: this unloads all the modules in the current scope.)
  It is a member of the hidden package `Cabal-2.4.0.1'.
  You can run `:set -package Cabal' to expose it.
  (Note: this unloads all the modules in the current scope.)

Access violation in generated code when executing data at 0xffffffff835683b8

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x6d7ddd60   0xffffffff835683b8
```

I get the same error when trying it on my other projects.
I should also note that when trying it a couple of months ago it worked perfectly.

**Comment by jneira** [comment]
Hi, i am afraid `Setup.hs` is not supported out of the box by ghcide. do you experience the problem opening other files of the project in the editor?

**Comment by LukaHorvat** [comment]
I don't think this is actually related to Setup.hs. I'm just running the `ghcide` command in my project directory, without naming any files or anything. This error about Setup.hs was always there before, but after that it would say it managed to load 47 out of 49 files or something and the queries would work after that. Now it just crashes. The same thing happens when I run it through VS Code, just without the Setup.hs part since I guess the extension does something smarter than just running the program with no parameters.

**Comment by LukaHorvat** [comment]
Just tried with the 0.2 release and the same thing happens there as well.

**Comment by LukaHorvat** [comment]
I bisected it. This is the commit that introduces the bug: 373c4060dfb4cef21fa40cc6085aa00abd040d5b

**Comment by pepeiborra** [comment]
Thanks for the report Luka. Given that you cannot share the project, is it possible to put a smaller repro together and share that? Another thing that would help is trying to repro in another platform (Linux, MacOs) in order to discard a Windows specific issue.

**Comment by pepeiborra** [comment]
closing as non actionable

**Comment by jneira** [comment]
@LukaHorvat please, open a new issue in the haskell-language-server project if you continue experiencing it with the last version
