### ISSUE TITLE
Go to definition doesn't work for record syntax

### ISSUE THREAD

**Issue by newhoggy** [haskell/ghcide#71]
Doesn't work for constructor

![image](https://user-images.githubusercontent.com/63014/64929940-3e515d80-d86f-11e9-8f57-35f925335529.png)

Doesn't work for fields

![image](https://user-images.githubusercontent.com/63014/64929942-414c4e00-d86f-11e9-85db-8b62dba23f74.png)

**Comment by cocreature** [comment]
Thanks for the bug report, that definitely sounds like something that we should fix. If you want to take a look yourself, my guess would be that [getSrcSpanInfos](https://github.com/digital-asset/ghcide/blob/7133f4192f8d11908e5fb4c3f52ca3af54a23459/src/Development/IDE/Spans/Calculate.hs#L45) is the culprit.

**Comment by jacg** [comment]
It seems to work fine here:

![constructor](https://user-images.githubusercontent.com/2570854/65230313-ee240680-dacd-11e9-8442-56cdefa3cd63.png)

... both for constructors and fields (though for fields it still refers to the position of the constructor).

Can you provide a minimal failing example?

**Comment by newhoggy** [comment]
I defined `person0` and `person1`.

The only time I get the popup is when I hover over the `Person` constructor in `person1`.

![image](https://user-images.githubusercontent.com/63014/65380614-6a168c80-dd22-11e9-9050-f170f1b6edf9.png)

And Go To Definition doesn't work anywhere in the `person0` case.

![image](https://user-images.githubusercontent.com/63014/65380622-7c90c600-dd22-11e9-9343-662be129d800.png)

![image](https://user-images.githubusercontent.com/63014/65380628-8dd9d280-dd22-11e9-9581-46315c8499f3.png)

**Comment by ndmitchell** [comment]
I get definitions for the `Person` constructor in both `person0` (due to https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Spans/Calculate.hs#L122) and `person1` (due to https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Spans/Calculate.hs#L121). I don't get information about `name` or `age` because it doesn't have any cases that examine the record fields. This whole piece of code was copied wholesale from Intero, upgraded through a few GHC versions, lightly hacked for "things that didn't work", and could do with someone giving it some love. However, it shouldn't be that hard to make it a lot more powerful. If using SYB was OK then finding all names and grabbing the nearest enclosing Loc would probably be perfect.

**Comment by jacg** [comment]
> If using SYB was OK

Has SYB been proscribed?

**Comment by ndmitchell** [comment]
SYB seems to be responsible for a lot of problems, e.g. https://github.com/haskell/haskell-ide-engine/issues/1371. It's not fast and it is memory hungry. That said, it is concise and if it can be formulated properly, it's probably correct by construction.

**Comment by jacg** [comment]
I got tired of trying to verify manually what works and what does not, so I wrote some automated tests, which you can find [here](/jacg/ghcide/commits/find-definition).

The one entitled "plain data constructor" passes while the one entitled "record data constructor" fails, which seems to agree with what @newhoggy observes above, as well as my own observations in both VSCode and Emacs; but it disagrees with what @ndmitchell observes above.

> I get definitions for the Person constructor in [...] person0 (due to https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Spans/Calculate.hs#L122) 

Removing line 122, has no observable effect on any of the tests I have written. (I have confirmed that removal of lines 120, 121, or 147 does break some of my tests).

**Comment by jacg** [comment]
> This whole piece of code [...] could do with someone giving it some love. 

I'd like to have a go, but would benefit immensely from some pointers on how best to get stuck in.

**Comment by ndmitchell** [comment]
@mpickering ported the hie code over as part of https://github.com/digital-asset/ghcide/issues/101#issuecomment-534498465. If we can use that implementation rather than our own that makes most sense - less code = better.

**Comment by mpickering** [comment]
I have wanted to experiment with [geniplate](http://hackage.haskell.org/package/geniplate-mirror), in
order to generate efficient traversal functions. That might be worth looking into.

**Comment by jneira** [comment]
I've just test it in hls and works for me, i guess it should work in ghcide too.
@newhoggy feel free to reopen if it is no the case
