### ISSUE TITLE
is ghcide broken on the ghc compiler code base?

### ISSUE THREAD

**Issue by zeta-00** [haskell/ghcide#715]
hello there,
i setup my (lorri+direnv+emacs-direnv) configuration with `ghc.nix's default.nix file` ( https://github.com/alpmestan/ghc.nix ). ghcide builds with ghc in the nix-shell, and when i when i check the `ghcide --version`, its there, but i ran into some issues. whenever i touch a new haskell file, when i open it, the ghcide lsp is activated and it works, but whenever i open a haskell file from the ghc code base, lorri returns red on the exporting env vars message, and ghcide breaks and returns the error message: `no such file or directory`? is ghcide broken on the ghc code base? are ghc's haskell files too large for ghcide to handle?

thanks in advance for helping me fix this issue.

**Comment by zeta-00** [comment]
here's the error ghcide returns:

[zeta@nixos:/ghc.nix]$ strace -f -o /tmp/trace ghcide
ghcide version: 0.2.0 (GHC: 8.8.3) (PATH: /nix/store/sdn0dabqvc1g25s8grq7sa9g13ax8fk7-ghcide-exe-ghcide-0.2.0/bin/ghcide)
Ghcide setup tester in /home/zeta/ghc/ghc.nix.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/4: Finding files to test in /home/zeta/ghc/ghc.nix
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "/home/zeta/ghc/ghc.nix/haskell-test.hs"
File:     /home/zeta/ghc/ghc.nix/haskell-test.hs
Hidden:   no
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  /home/zeta/ghc/ghc.nix/hadrian/hie-bios: streamingProcess: runInteractiveProcess: exec: does not
  exist (No such file or directory)
Files that failed:
 * /home/zeta/ghc/ghc.nix/haskell-test.hs

Completed (0 files worked, 1 file failed)
(lorri) 
[zeta@nixos:/ghc.nix]$

**Comment by Mic92** [comment]
@zeta-00 you also need to upload the file in /tmp/trace.

**Comment by pepeiborra** [comment]
Hello there zeta! 

ghcide is known to work well with the ghc codebase and indeed, several ghc developers use either ghcide or its close relative Haskell-language-server. But it's not a trivial setup, you need to have a basic understanding of hie-bios and bios cradles, Hadrian, the ghc configure/boot details, and how it all fits together. Adding ghc.Nix to that equation isn't going to help either.

My recommendation is that you take your time to review all the materials, depending on what you are intending to do, and hang out in the ghc and haskell-ide-engine IRC channels. 

Please close this issue now as there is no ghcide issue here.

**Comment by Mic92** [comment]
I don't know much about haskell but judging the error message, there should be a program missing that `hie-bios` cannot executed. Therefore grep for `execve` in `/tmp/trace`.
