### ISSUE TITLE
Loading multiple standalone files without any hie.yaml file started giving import errors.

### ISSUE THREAD

**Issue by maralorn** [haskell/ghcide#765]
I am currently working with the test added in https://github.com/maralorn/ghcide/commit/bd3290889152b7a63b53e32077b5b348c93ae2d1

This test started failing with `"Could not find module "B". It is not a module in the current program, or in any known package."`

Sometime in the last week.

**Comment by pepeiborra** [comment]
In this case the fix is to add a `hie.yaml` cradle, probably a direct one for simplicity.

In the general case, using ghcide without any cradle means falling back to the implicit cradle, and that is currently not very well defined at all - I don't think hie-bios supports that scenario very well, perhaps tools like [implicit-hie](https://hackage.haskell.org/package/implicit-hie) could be used to generate a sensible default cradle instead. @wz1000  @fendor thoughts?

**Comment by maralorn** [comment]
I can confirm that I added a simple `hie.yaml` cradle, that worked fine. But it worked without before and it would be nice if it would again I think.

**Comment by fendor** [comment]
> I don't think hie-bios supports that scenario very well

I agree, it does not.

@maralorn Did you change anything? E.g., new ghcide version? I assume the changes from https://github.com/wz1000/ghcide/pull/10 cause this behaviour, as ghcide used to find files on its own, which worked for the trivial case and hie-bios does not attempt to find any targets at all, e.g. we do not perform a downsweep from the module to load (which would probably not found this issue anyways).

A possible work-around for multiple files could be the implicit cradle assumes the import path "-i." and then searches the disk for possible targets?

**Comment by pepeiborra** [comment]
@fendor what has changed is that ghcide removes all import paths from the GHC HscEnv:

https://github.com/haskell/ghcide/blob/master/src/Development/IDE/GHC/Util.hs#L188-L192

This is necessary to prevent GHC from loading files on its own, bypassing ghcide and hie-bios, which leads to bugs in bios cradles that specify different settings for modules in the same folder. 

Your suggestion could be implemented by not removing the import paths from the HscEnv for implicit cradles. The alternative is to have implicit-hie generate a direct cradle that enumerates all source files under the current directory recursively, but for that we'd need to integrate implicit-hie into ghcide or HLS. Thoughts?

**Comment by fendor** [comment]
> This is necessary to prevent GHC from loading files on its own, bypassing ghcide and hie-bios, which leads to bugs in bios cradles that specify different settings for modules in the same folder.

Right, that makes sense to me.

> Your suggestion could be implemented by not removing the import paths from the HscEnv for implicit cradles. 

Exactly. Currently I am wondering what would happen if you add/remove a module. Would it create a new component? We should probably merge those... 

> The alternative is to have implicit-hie generate a direct cradle that enumerates all source files under the current directory recursively

Yeah, that was basically what I meant, too. Still, the problem of adding modules still persists.
I don't see a problem with integrating implicit-hie into ghcide and hls. Personally, I think it would be a good idea.

**Comment by pepeiborra** [comment]
When ghc loads files on its own the cradle doesn't get queried, and we don't create a new session. It looks like the simplest solution to restore the previous behaviour is to not remove the import paths for implicit cradles. I'll do that.
