### ISSUE TITLE
(Windows, Stack) Documentation / Source links don't appear for base libraries, only for stackage

### ISSUE THREAD

**Issue by DunetsNM** [haskell/ghcide#769]
### Environment

Windows 10
stack 2.3.3
reproduced for GHC 8.6.5 and 8.10.1

built with haddock flag

### Symptoms

Links to docs and sources in tooltips appear just fine for libraries _from stackage_ (also not always atm, but it's a different story and there's a PR for it: https://github.com/haskell/ghcide/pull/766)
Stackage snapshots stored locally at `C:\sr\snapshots\`

aeson toJSON works fine:
![image](https://user-images.githubusercontent.com/5116838/92319468-a7c41080-f06c-11ea-80ff-8f3cb50a2c7a.png)

But doc links don't appear for _base libraries_, stored at the stack ghc installation e.g. `c:\Users\KolA\AppData\Local\Programs\stack\x86_64-windows\ghc-8.10.1\doc\html\libraries`

no luck for Data.Text T.pack:
![image](https://user-images.githubusercontent.com/5116838/92319569-cecf1200-f06d-11ea-9e28-4d15e2bb55a5.png)

According to [the video in this post](https://mpickering.github.io/ide/posts/2020-07-10-ghc-libdir.html) it works fine on Mac (at least for T.pack), so I think it is Windows-specific.

### Cause

I fiddled with `Development.IDE.Spans.Documentation` and found out that `lookupHtmls` returns following directory for base/prelude stuff: 

for GHC 8.6.5 : `$topdir/../doc/html/libraries/base-4.12.0.0`
for GHC 8.10.1 : `$topdir/../doc/html/libraries/base-4.14.0.0`

assuming that $topdir is a synonym for location of ghc.exe (e.g. `c:\Users\KolA\AppData\Local\Programs\stack\x86_64-windows\ghc-8.10.1\bin\`) it should resolve documentation directory correctly however it doesn't.

As a matter of fact base docs just as well stored at snapshots directory `C:\sr\snapshots\` ! but with different subpath (no /html/libraries/ part - e.g. `c:\sr\snapshots\1b8f3c61\doc\base-4.14.0.0` )

### What to do?

I'm keen to fix it but not sure where to look for the root cause.   Should I look upstream in LSP ? in Stack ? Or in GHC itself ? Any hints appreciated.

**Comment by ndmitchell** [comment]
My inclination would be take a two pronged approach:

1. It looks a bit like Stack is wrong here, since it is missing html/libraries. Would be good to know if that is a Stack on all platforms, or a Stack on Windows. Can we raise a bug for Stack? Can they fix it? Maybe its the GHC packaging itself on Windows, so try with a GHC installed direct from GHC HQ.
2. At the same time, getting the fixes upstream is good, but will take multiple release cycles to sort out. I'd change whatever it is that produces source links, and add a doesFileExist test near them. If the file doesn't exist, don't display a source link. Moreover, if you can hypothesise where the right file might be (e.g. chop out `html/libraries`) I'd give that a go and repeat the does file exist. That way we might be able to work around the issue and display source links before its fixed upstream.

**Comment by DunetsNM** [comment]
> Would be good to know if that is a Stack on all platforms, or a Stack on Windows.

OK it's not Stack on all platforms: it appears for ghcide compiled on Ubuntu (in Windows WSL)

![image](https://user-images.githubusercontent.com/5116838/93296372-29712680-f843-11ea-9a47-bee8f2eb9058.png)

Documentation for `T.pack` points to the stack-sandboxed GHC which is correct: 
`~/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/share/doc/ghc-8.6.5/html/libraries/text-1.2.3.1/`

It might be Stack on Windows but I haven't tried naked GHC yet to confirm it. Quick googling of `haddock ghc windows "$topdir"` gives a hint that problem is old and reappears here and there at least since 2006.

**Comment by DunetsNM** [comment]
Figured it out. The issue is that ghcide looks up docs directory via `haddockHTMLs`  of `PackageConfig`.  Other similar fields of `PackageConfig` that contain relative paths (haddockInterfaces, libraryDirs, libraryDynDirs ...) have `$topdir` substituted properly on Windows but haddockHTMLs left intact and it seems like deliberate decision because unlike other fields it can be either URL or a path.

Here's the related code in Cabal and GHC:

https://github.com/haskell/cabal/blob/2a5f1e7ac37b3a2cbcc5dc78e6f9fa0fbc6dc445/Cabal/src/Distribution/Simple/Program/HcPkg.hs#L307

https://gitlab.haskell.org/ghc/ghc/-/blob/8af954d202de1de0671062c3f55e43fc783f8192/libraries/ghc-boot/GHC/Unit/Database.hs#L697

So the next best thing I could do, instead of `haddockHTMLs` use `haddockInterfaces` and trim the file name from it to get the directory.
