### ISSUE TITLE
Drop GHC 8.4.x support

### ISSUE THREAD

**Issue by pepeiborra** [haskell/ghcide#803]
I am thinking that we can drop 8.4.x as soon as we upload a new version to Hackage.
If anyone has concerns about this, please discuss them here

**Comment by pepeiborra** [comment]
We are keen on dropping since HIE files cannot be easily back ported to 8.4.x and we cannot afford to maintain two code paths for typechecking, hover and gotodef. This is blocking the merge of changes from the hls-3 branch.

**Comment by ndmitchell** [comment]
Fine by me - I have no preferences or restrictions on what you drop.

**Comment by cocreature** [comment]
Fine with me, I never needed 8.4 support personally or at work. @ndmitchell was originally advocating for adding it but that was a while back.

**Comment by jneira** [comment]
Support definitely droped with #834
