### ISSUE TITLE
Fix Windows CI caching and reenable Windows CI

### ISSUE THREAD

**Issue by pepeiborra** [haskell/ghcide#805]
If you could fix the caching for the Windows CI I would be eternally grateful. Otherwise I might have to disable since the network connection to the stackage infrastructure (`casa.fpcomplete.com`) has become very unreliable and stack builds fail all the time

_Originally posted by @pepeiborra in https://github.com/haskell/ghcide/pull/794#discussion_r488124365_

**Comment by jneira** [comment]
The last succesful build with windows was https://dev.azure.com/digitalasset/ghcide/_build/results?buildId=55020&view=results
There are failed ones after it with timeouts, so, to be sure, what do you mean with `fix the caching for the windows CI`? was it always missing?

**Comment by jneira** [comment]
Ok, let's take the first build of #808:

* two linux jobs (84 and bench) throwed a build time out (reported as canceled)
* and windows one throwed a time out downloading packages from stack

```
HttpExceptionRequest Request {
  host                 = "casa.fpcomplete.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/v1/pull"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
```

Maybe we could retry the build of dependencies, to try to recover for thos ones

**Comment by pepeiborra** [comment]
Windows build take so long because the Azure cache is not being used by stack. This also makes them more flaky, as stack has a non-zero chance of failing to connect to `casa.fpcomplete.com`.
