### ISSUE TITLE
Test suite has ghcide in build-tool-depends but uses it from global $PATH

### ISSUE THREAD

**Issue by jneira** [haskell/ghcide#817]
* The test suite has ghcide in the `build-depends` field in the `ghcide.cabal` file, triggering the build of the executable locally but without installing it globally (afaiu watching the build log)
* Then the test suite uses ghcide from global path so you have to manually install it before running the suite:

https://github.com/haskell/ghcide/blob/153536bda11fbf1ebee8434aa981911db73d09b8/test/cabal/Development/IDE/Test/Runfiles.hs#L8-L9

It should call `cabal run ghcide` or `stack exec ghcide`, to use the actual ghcide version or am i misssing something obvious?

**Comment by fendor** [comment]
We should probably use `build-tool-depends` https://cabal.readthedocs.io/en/3.4/cabal-package.html?highlight=build-depends#pkg-field-build-tool-depends. This puts the executable on the PATH, afaict.

**Comment by jneira** [comment]
wow, i did not remember that, thanks!

**Comment by jneira** [comment]
@fendor sorry i misreaded the cabal file, it is already using `build-tool-depends` and although it does not a global install, makes the tool available in the test suite
