### ISSUE TITLE
Disable highlighting of (other occurences of) thing at point

### ISSUE THREAD

**Issue by slotThe** [haskell/ghcide#856]
For context, I'm using `ghcide` HEAD with `Emacs` 28 and `eglot` 20200830.1254.

This is the behaviour I'm talking about: 

![example](https://i.imgur.com/gjhGft4.png)

I find this hugely distracting and so I would like to disable it.  I guess the more general question here is "is it possible to disable features and, if yes, is this the responsibility of `ghcide` itself or whatever LSP client one is using?"

**Comment by ndmitchell** [comment]
Does this occur with other languages? And plain text files? I see the same behaviour with VS Code, but I see it on plain text files too, so I might be nothing to do with Ghcide.

**Comment by alanz** [comment]
This is a feature of LSP, but I think vscode does its own dumb version too, just on word match.
The feature is [Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentHighlight), and the LSP version uses the actual scope, so is not confused by name shadowing etc. It also highlights differently for where the value is set, vs read.

Personally I like it, but have set the color scheme in my emacs to be unobtrusive, the default *is* too in your face

**Comment by michaelpj** [comment]
I think this is probably the responsibility of elglot. And, indeed, it looks like it provides a mechanism for customizing this, with document highlighting as an example: https://github.com/joaotavora/eglot/blob/master/eglot.el#L1191

**Comment by slotThe** [comment]
On Fri, Oct 09 2020 08:06, Michael Peyton Jones wrote:
> I think this is probably the responsibility of elglot. And, indeed, it
> looks like it provides a mechanism for customizing this, with document
> highlighting as an example:
> https://github.com/joaotavora/eglot/blob/master/eglot.el#L1191

That worked perfectly, thanks!  Even obvious things like this can be
really hard to find when you're not exactly sure what you're looking
for...

**Comment by michaelpj** [comment]
Yeah, I think we still need to say more about configuration in the readme.
