### ISSUE TITLE
Insert inferred types as decorations

### ISSUE THREAD

**Issue by ndmitchell** [haskell/ghcide#88]
VS Code has a mechanism called decorations which is used by various extensions (e.g. Rust, F#, TypeScript) to insert the inferred types into the documents, as comments, but which aren't really there in the source. See https://marketplace.visualstudio.com/items?itemName=MartinJohns.inline-types for a nice screenshot and simple editor (simple enough you could take the code as a starting point) and the VS Code introduction https://vscode.rocks/decorations/.

I think this would be super handy on top-level functions that don't have types, but Rust puts it on pretty much every binding and it can be quite useful there too.

Related to #81 and #77.

**Comment by serras** [comment]
Maybe [code lens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) could provide a nicer UI for top-level definitions?

**Comment by ndmitchell** [comment]
If you did it as a code lens on top-level definitions then clicking the lens could insert the type into the document. That would be a very smooth experience.

**Comment by serras** [comment]
This can be closed, right?

**Comment by jneira** [comment]
closing, as the feature is already included
