### ISSUE TITLE
Import syntax is a parse error

### ISSUE THREAD

**Issue by Fresheyeball** [haskell/ghcide#881]
Haskell language server correctly suggest the following change

```haskell
import Servant.API
```

to 

```haskell
import Servant.API (type (:<|>)(..), Capture, JSON)
```

Which compiles fine. But Haskell language server reports it as a parse error.

**Comment by jneira** [comment]
@Fresheyeball pehaps the last "haskell language server" should be "ghcide"?

**Comment by pepeiborra** [comment]
I think [ExplicitNamespaces](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-ExplicitNamespaces) is needed to parse that import. 

HLS/ghcide use the suggestions in GHC error messages to generate code actions, so if GHC is suggesting this import but not suggesting the language extension that's probably a bug in GHC. Please check and consider opening an issue in the GHC bug tracker

**Comment by pepeiborra** [comment]
Closing as nothing to do here
