### ISSUE TITLE
Example of including ghcide into shell.nix

### ISSUE THREAD

**Issue by ingun37** [haskell/ghcide#885]
Your README.md says

> Install by including pkgs.haskellPackages.ghcide in your projects shell.nix.

without further explanation.

I guess it's supposed to be easy but I find it really hard as a nix new-comer.

Can you help me by giving a quick example?

**Comment by trodrigu** [comment]
@ingun37 I'm still learning very much so but I was able to get ghcide in my nix-shell session via `nix-env -i -f '<nixpkgs>' -E 'pkgs: (pkgs {}).ghc.withPackages (hp: with hp; [ ghcide ])'`.  I'm still trying to figure out how to add it to my shell.nix

**Comment by ingun37** [comment]
@trodrigu I ended up using [haskell-language-server](https://github.com/haskell/haskell-language-server). I think it superseded *ghcide*.

**Comment by fendor** [comment]
Not quite, ghcide is the workforce behind haskell-language-server and haskell-language-server implements a lot of plugins on top of ghcide, but ghcide itself is still very much developed and in use and not superseded.

**Comment by ingun37** [comment]
@fendor My bad. Thank you for correcting my misunderstanding. BTW I'm closing the issue because it's no longer bothering me.
