### ISSUE TITLE
Mixins are not accounted when trying to hide Prelude

### ISSUE THREAD

**Issue by Martoon-00** [haskell/ghcide#890]
## Problem

In one of the projects, we are trying to use `mixins` feature to hide the default `Prelude` module and provide our own, in overall this looks like

```yaml
# package.yaml
depedencies:
  - name: base
    version: ">= 4.7 && < 5"
    mixin: [hiding (Prelude)]
  - morley-prelude
```

However, it looks like hiding `Prelude` does not work, because with ghcide I get the following error

```
Ambiguous module name ‘Prelude’:
  it was found in multiple packages:
  base-4.13.0.0 morley-prelude-0.3.0
```

## Reproduction

I can reproduce this in the [Morley repository](https://gitlab.com/morley-framework/morley/), commit `e9a00b61bb`.
It has `morley-prelude` package used as a custom prelude. When I open some of the depending packages, e.g. `code/morley/src/Util/Text.hs` file from `morley` package, I get the mentioned error for all modules. 
There are other packages using `morley-prelude` where the problem reproduces, e.g. [`morley-ledgers`](https://gitlab.com/morley-framework/morley-ledgers/-/tree/552774ec4fe8a9da6afc77bbae31c30483402b9a) has much less modules (in case that is helpful), but it appears in a different repository. 

## Side comments

Indeed, one of the options for us would be just not using mixins and instead use `base-noprelude`. We are going to apply this as a temporary workaround, though it would be nice if this feature is eventually supported.

I'm not sure how problematic this may be to fix, since it is a known issue that even `stack ghci` [does not work](https://github.com/commercialhaskell/stack/issues/5077) with mixins properly, but would be nice to at least know your plans on this.

**Comment by wz1000** [comment]
> I'm not sure how problematic this may be to fix, since it is a known issue that even stack ghci does not work with mixins properly, but would be nice to at least know your plans on this.

This might be linked, since `ghcide` gets its flags by asking `stack` for them. Have you tried using a cabal cradle? Otherwise try `hie-bios check SomeFile.hs`, or running `ghci` with the flags returned by `hie-bios dump`.

**Comment by Martoon-00** [comment]
I have some severe issues with making `cabal` work.

`hie-bios check` reports the same `Ambiguous module name ‘Prelude’ ...` error.

Tried `hie-bios dump`, though somehow it doesn't have such a command (using `hie-bios version 0.5.1 compiled by GHC 8.8.3`)

**Comment by wz1000** [comment]
Sorry, I meant `hie-bios flags`.

However, `hie-bios check` not working means this is likely an upstream issue with the flags `stack` is telling us to use.

**Comment by jneira** [comment]
I think it could be `hie-bios debug`.
As @wz1000 commented `stack repl` does not work with `mixin` and `hie-bios` needs to call `stack repl` underneath to give build info to ghcide. stack issue is https://github.com/commercialhaskell/stack/issues/5077
So i am afraid that there is no much to do but use cabal ot not use mixins

**Comment by Martoon-00** [comment]
`hie-bios flags` / `debug` mention `-package-id=base-4.13.0.0` among options without mentioning mixins, and if those flags are all the information provided by `hie-bios` for compilation, then apparently this is there the attempt to hide `Prelude` fails.

If there are other issues with `hie-bios` like the one you mentioned, that it needs `stack repl`, then things are even sadder.

I suppose I will report an issue in `hie-bios` then and close this issue until something changes upstream. Thanks for the quick reply!
