### ISSUE TITLE
How to ignore "Defined but not used:" warnings?

### ISSUE THREAD

**Issue by anka-213** [haskell/ghcide#901]
I'm in a [repo](https://github.com/GrammaticalFramework/gf-core/) where `-Wall` is *not* enabled and hasn't been for decades. Despite this, the problems tab is filled with thousands of `Defined but not used: ‘foo’ typecheck` warnings, which makes the problems tab kind of useless. 

How do I disable those warnings and where do they come from in the first place? `stack build` does not give any such warnings.

**Comment by wz1000** [comment]
https://github.com/haskell/ghcide/pull/815 might be responsible.

**Comment by anka-213** [comment]
Does #907 resolve this issue? I love the unused variables being grayed out, but having them all appear in the "problems" tab is too much.

As an answer to my question in the title: A workaround in VS Code is to press the "filter" button and ignore everything of level "info".

**Comment by jneira** [comment]
@anka-213 i think #907 should resolve this, have you got ant chance to try it?

**Comment by pepeiborra** [comment]
Closing as allegedly solved. Feel free to open a new issue in haskell/haskell-language-server if that's not the case.
