### ISSUE TITLE
Error opening ghcide project in VSCode with the ghcide/haskell extension installed

### ISSUE THREAD

**Issue by samuela** [haskell/ghcide#925]
I just installed the official VSCode ghcide/haskell extension, cloned the ghcide repo, and then tried opening `src/Development/IDE.hs`. The issue repeats after reloading the window.

![Screen Shot 2020-11-27 at 5 16 05 PM](https://user-images.githubusercontent.com/226872/100490942-b6065380-30d4-11eb-9eda-71fc8fbf59af.png)

I looked for more logs, but I couldn't find anything "Extensions" or "Log (Extension Host)" in the Output pane unfortunately. Happy to report any other logs, but unsure where else to look.

VSCode version: 1.51.1
Haskell extension: 1.2.0
GHC 8.10.2, cabal 3.2.0.0 installed via ghcup
macOS: 10.15.4

**Comment by samuela** [comment]
Ok, fixed after running `cabal update`. So I guess this is an issue that ghcide fails un-gracefully when cabal's index is out-of-date.

**Comment by samuela** [comment]
I also received this same error today in hover form:

![Screen Shot 2020-12-08 at 4 56 27 PM](https://user-images.githubusercontent.com/226872/101559612-52064980-3976-11eb-8c43-a292b19323d8.png)

Also fixed with `cabal update`.

**Comment by jneira** [comment]
Not sure if ghcide or hls, via hie-bios will handle that cabal misconfiguration, as a auto cabal update might break things (cabal itself does not run it auto for that reason). Otoh `stack`, with other defaults, does it.
But maybe it could display a more helpful error.

**Comment by samuela** [comment]
Yeah it would be great to get a clearer error message here, ideally with a snazzy little "Run cabal update" button too.

**Comment by pepeiborra** [comment]
The way I see it, this is a Cabal issue. Ghcide is merely a conduit, using the build system that you chose to build your project. It is not Ghcide's place, in my mind, to be parsing the build system unstructured error messages to try and compensate for the lack of accessibility. 

From that point of view, I am closing this ticket. If you disagree please feel free to reopen, or even better, to send a PR with your purported solution.

**Comment by samuela** [comment]
I'm not intimately familiar with the haskell ecosystem and I do hear what you're saying here, but I would argue that what matters at the end of the day is: Does it "just work" for users? The rust ecosystem is a great example of this. They have standardized on a build system (cargo), and everything "just works". Ie, the rust-language-server integration with cargo is very nice, and as a result it's able to offer a best-in-class experience. Easier said than done, to be sure.

On a meta-point, it seems to me that any language server implementation must integrate with a build system to some extent. One of the language server's central goals is to answer questions like "does this code build?", etc. And to me that suggests a necessary coupling between the two.

Some naive questions:
* Does cabal not offer a programmatic interface? Cargo has convenient output options including [json](https://doc.rust-lang.org/cargo/reference/external-tools.html#json-messages).
* Does haskell have competing build systems besides cabal? I'm aware of stack, but my understanding was that it still relied on cabal under the hood. What does the ghcide/build system interface look like?
* From a technical perspective, what needs to happen to get tighter integration between ghcide and cabal/stack/etc? What are the major challenges here?

**Comment by ndmitchell** [comment]
@samuela - I also use both Rust and Haskell, and agree Rust has a lot better integration. But it's not that easy:

* Cabal doesn't offer a programmatic interface yet :( - it even offers 4 entirely incompatible build commands (v1-build, v2-build, build, new-build).
* Haskell has Cabal, Stack (which is kind of using Cabal, rather than wrapping Cabal), Nix, Obelisk, Buck, Bazel. And then GHC itself can build stuff too.

Our solution was to farm all this under an abstraction layer called hie-bios - https://github.com/mpickering/hie-bios. That is responsible for figuring out which build system to call, and how to call it. As tools get programmatic interfaces (which is on the todo list for basically all of them), that can make use of them. If we could get structured errors out of hie-bios, we'd use them. But it's a hie-bios problem.

I'd be happy with some specific asks moving over to hie-bios - e.g. failures having structured errors, and failures returning any remediation or when to retry information.

Unfortunately, the whole thing is vastly more fragmented than Rust, which makes the tight integration Rust does unsuitable for Haskell :(

**Comment by samuela** [comment]
Thank you for the clarification @ndmitchell! That clears things up a lot for me. I didn't realize that this layer had been separated out into hie-bios. 

It sounds like the technical challenges here are to expose programmatic interfaces for the build systems of interest (cabal, stack, nix, bazel, etc), and then get that information relayed through hie-bios. Then something useful can be made of it in ghcide.

**Comment by jneira** [comment]
well imho we (the right component would be hie-bios) could do some effort to alliviate the lack of usability of the build tools while they are improved (and there are no deadlines I am afraid)
We are already doing it for ghc and the build tools themselves, with a bunch of hacks. So one more for get useful errors for final users would worth the effort.

That said, our human power is limited and there are many issues to fix and improvements to implement. 😟

**Comment by samuela** [comment]
@jneira Are there any delegate-able well-scoped tasks that contributors could help you out with?
