### ISSUE TITLE
Bug with valid hole fit substitutions: they do not respect scope!

### ISSUE THREAD

**Issue by Tritlo** [haskell/ghcide#932]
Here's the part of my stream where this happened live:
https://youtu.be/lfrk0wyZHvg?t=2311

(don't forget to like and subscribe /s)

What happens is that it suggests `lookup`, whereas the `IntMap` module was imported as a qualified, meaning that it has to be `IM.lookup`. It works correctly in the raw GHC output, but not in GHCIDE itself.

**Comment by jneira** [comment]
Hi, thanks for report this with a live demo included!
I think that bug was reported in #726 so i am gonna close this one, mentioned video in the original one.
Feel free to reopen if that is not the case.
