### ISSUE TITLE
Deprecate the ghcide executable

### ISSUE THREAD

**Issue by pepeiborra** [haskell/ghcide#935]
We have already told people to not use ghcide directly: 

https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html

The next logical step is to deprecate and eventually remove the ghcide executable.

/cc @cocreature @ndmitchell any concerns?

**Comment by wz1000** [comment]
I think it makes sense to keep it around for purposes of ghcide development itself.

**Comment by cocreature** [comment]
I’m fine with deprecating it as a user-facing feature but for tests and development it seems pretty useful and afaict it’s cheap to keep around.

**Comment by ndmitchell** [comment]
It might make sense to deprecate the extension at https://marketplace.visualstudio.com/items?itemName=DigitalAssetHoldingsLLC.ghcide, and I've no concern about removing features like completions (unless @cocreature does), but I don't think that deprecating it beyond that would mean much.
